services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command:
      pnpm run dev
 
  db:
    image: postgres:16.0-alpine3.18
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  requestly:
      image: hoppscotch/hoppscotch
      container_name: hoppscotch_container
      restart: always
      ports:
        - "3001:3001"

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin4_container
      restart: always
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: benshigregg@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin